@startuml


#LightBlue: The user requests a withdrawal;

#White:The client application sends
a notification to the owner;

#LightGrey:if (The owner rejects it within the
specified confirmation time?) then (yes)
  #White:The withdrawal is cancelled
  and the contract rejects
  new withdrawals until opened
  or killed by the owner;
else (no)
  #White:The client application sends
  a notification to the user;
  #LightBlue: The user can confirm the
   transaction => the funds
   are transferred;

@enduml